### GENERAL SETTINGS ###

# Site settings
title: Meowing Dolphins
description: "The Meowing Dolphins Online Resource Kit for FIT2003, Semester 1 2015."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://meowingdolphins.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#FF0052" #"#F70031"
  primary_rgb: "255,0,82" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#442C50" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Taste Baguette
    - Monash University Clayton Campus
    - 3800, Victoria
    - Australia
email: meowingdolphins@dolphinmail.com
tel: 1800 Dolphin


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Clare Hosford
    position: Lead Dolphin
    img: clare.jpg
    social:
      - title: envelope #use for email address
        url: mailto:cehos1@student.monash.edu
  - name: James Liu
    position: Design Dolphin
    img: james.jpg
    social:
      - title: envelope #use for email address
        url: mailto:jyliu8@student.monash.edu
  - name: Zhuang Shao
    position: Support Dolphin
    img: zhuang.jpg
    social:
      - title: envelope #use for email address
        url: mailto:zsha25@student.monash.edu
  - name: Avital Ternovsky
    position: Editing Dolphin
    img: avital.jpg
    social:
      - title: envelope #use for email address
        url: mailto:ater6@student.monash.edu
  - name: David Tran
    position: Planning Dolphin
    img: david.jpg
    social:
      - title: envelope #use for email address
        url: mailto:mttra10@student.monash.edu

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "The Meowing Dolphins were established in April of 2015 as a fine group of procrastinators and resource-gatherers. The Dolphins' diet include various food items available at Taste Baguette, but not including those on the expensive side of the menu. We're happy to accept donations for meals at anytime."